---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-application
          image: flask-app-k8s
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CONSUL_IP
              value: 192.168.0.108 # This is just a hardcoded Consul URL as i havent put it on k8s yet
